feat(vm): Add resource cloudavenue_vm_inserted_media
orange-cloudavenue/terraform-provider-cloudavenue pull request #126
Opened 2023-02-28 13:42 UTC by dmicheneau

If you submit change in the provider code, please make sure to:

- [ ] Write or modify examples in `examples/` directory
- [ ] Write or modify acceptance tests
- [ ] Run `make generate` to ensure the doc was updated properly

### How has this code been tested
```
TF_ACC=1 go test -v ./internal/tests/vm -run TestAccVMInsertedMediaResource
=== RUN   TestAccVMInsertedMediaResource
--- PASS: TestAccVMInsertedMediaResource (15.49s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vm  15.507s
```

2023-02-28 14:17 UTC, azrod requested changes

2023-02-28 14:17 UTC, azrod commented on internal/provider/vm/vm_inserted_media_resource.go
> +// NewVappVMInsertedMediaResource is a helper function to simplify the provider implementation.
Bad comment

2023-02-28 14:17 UTC, azrod commented on internal/provider/vm/vm_inserted_media_resource.go
> +}
```suggestion
func (r *vmInsertedMediaResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_" + categoryName + "_" + "inserted_media"
}
```

2023-02-28 14:17 UTC, azrod commented on internal/provider/vm/vm_inserted_media_resource.go
> +			"id": schema.StringAttribute{
Please add Description

2023-02-28 14:17 UTC, azrod commented on internal/provider/vm/vm_inserted_media_resource.go
> +		MarkdownDescription: "The inserted_media resource allows you to manage a ...",
Please finish this description

2023-02-28 14:17 UTC, azrod commented on internal/provider/vm/vm_inserted_media_resource.go
> +			},
VDC doesn't require replace ?

2023-02-28 14:17 UTC, azrod commented on internal/provider/vm/vm_inserted_media_resource.go
> +		resp.Diagnostics.AddError("Media not mounted", "Media is not mounted on the VM")
Add `resp.Diagnostics.RemoveResource(ctx)`

2023-02-28 14:17 UTC, azrod commented on internal/tests/vm/vm_inserted_media_resource_test.go
> +			// },
Remove your comment

2023-02-28 14:17 UTC, azrod commented on internal/provider/vm/vm_inserted_media_resource.go
> +// Package vm provides a Terraform resource.
Please rename your file `inserted_media_resource.go`

2023-02-28 14:18 UTC, azrod commented on docs/resources/vm_inserted_media.md
> +subcategory: ""
Please add Subcategory

2023-02-28 14:20 UTC, azrod reviewed
.

2023-02-28 14:24 UTC, azrod commented on internal/tests/vm/vm_inserted_media_resource_test.go
> +// Package vm provides the acceptance tests for the provider.
Please rename your file `inserted_media_resource_test.go`

2023-02-28 14:25 UTC, azrod reviewed
.

2023-02-28 14:41 UTC, dmicheneau commented on internal/provider/vm/vm_inserted_media_resource.go
> +		resp.Diagnostics.AddError("Media not mounted", "Media is not mounted on the VM")
fix by: resp.State.RemoveResource(ctx)

2023-02-28 15:41 UTC, azrod requested changes

2023-02-28 15:41 UTC, azrod commented on internal/client/client.go
> +	c.Vmware = govcd.NewVCDClient(*c.urlVmware, false, govcd.WithAPIVersion("37.0"))
Please create specific PR for this change

2023-02-28 15:41 UTC, azrod commented on templates/resources/vm_inserted_media.md.tmpl
> +  Only one media is allowed per VM.
```suggestion
~> Note:  Only one media is allowed per VM.Only one media is allowed per VM.
```

2023-02-28 15:41 UTC, azrod commented on templates/resources/vm_inserted_media.md.tmpl
> +subcategory: "VM"
```suggestion
subcategory: "VM (Virtual Machine)"
```

2023-02-28 16:10 UTC, azrod requested changes

2023-02-28 16:10 UTC, azrod commented on templates/resources/vm_inserted_media.md.tmpl
> +  Note: Only one media is allowed per VM.
`~>` Add Warning Block in terraform doc. 
Preview result in [doc-preview](https://registry.terraform.io/tools/doc-preview)
```suggestion
 ~> Note: Only one media is allowed per VM.
```

2023-02-28 16:23 UTC, azrod commented on templates/resources/vm_inserted_media.md.tmpl
> +  ~> Note: Only one media is allowed per VM.
```suggestion
~> Only one media is allowed per VM.
```

2023-03-01 10:43 UTC, azrod approved these changes

2023-03-01 13:30 UTC, merged