feat(vapp): add `cloudavenue_vapp_acl` resource
orange-cloudavenue/terraform-provider-cloudavenue pull request #158
Opened 2023-03-08 17:06 UTC by gaetanars

### Description of your changes
This PR onboard a new resource and some commons for vapp and vdc.

If you submit change in the provider code, please make sure to:

- [x] Write or modify examples in `examples/` directory
- [x] Write or modify acceptance tests
- [x] Run `make generate` to ensure the doc was updated properly

### How has this code been tested
```
❯ TF_ACC=1 go test -run TestAccAccessControlResource -v -count=1 ./internal/tests/vapp
=== RUN   TestAccAccessControlResource
--- PASS: TestAccAccessControlResource (8.49s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vapp        8.495s
```

2023-03-08 20:00 UTC, eremid commented
acl or access_control ?
https://github.com/orange-cloudavenue/terraform-provider-cloudavenue/issues/112#issuecomment-1440697092

2023-03-09 06:33 UTC, gaetanars commented
You’re right, acl works fine. I modify this.

2023-03-09 08:56 UTC, eremid requested changes

2023-03-09 09:03 UTC, gaetanars commented on internal/provider/common/acl/acl.go
> +func Schema() map[string]schema.Attribute {
Done

2023-03-09 10:33 UTC, eremid requested changes

2023-03-09 10:33 UTC, eremid commented on internal/provider/vapp/acl_resource.go
> +func (r *aclResource) createOrUpdateacl(ctx context.Context, rm *aclResourceModel) (diag diag.Diagnostics) {
createOrUpdateacl =>  createOrUpdateACL ?

2023-03-09 11:17 UTC, eremid approved these changes

2023-03-09 11:37 UTC, merged