feat(network): add datasource `cloudavenue_network_routed`
orange-cloudavenue/terraform-provider-cloudavenue pull request #249
Opened 2023-03-31 12:13 UTC by valentin-dubreuil

### Description of your changes

Add datasource `cloudavenue_network_routed`

If you submit change in the provider code, please make sure to:

- [ ] Write or modify examples in `examples/` directory
- [ ] Write or modify acceptance tests
- [ ] Run `make generate` to ensure the doc was updated properly

### How has this code been tested
```
=== RUN   TestAccNetworkRoutedDataSource
--- PASS: TestAccNetworkRoutedDataSource (4.90s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/network     4.912s
```

2023-03-31 16:08 UTC, azrod requested changes

2023-03-31 16:08 UTC, azrod commented on internal/provider/network/routed_datasource.go
> +	Gateway       types.String `tfsdk:"gateway"`
Add `EdgeGatewayName` in addition to `EdgeGatewayID`

2023-03-31 16:08 UTC, azrod commented on internal/provider/network/routed_datasource.go
Warning use latest version of `terraform-templates`

2023-03-31 16:08 UTC, azrod commented on internal/provider/network/routed_datasource.go
> +	resp.TypeName = req.ProviderTypeName + "_" + "network_routed"
```suggestion
	resp.TypeName = req.ProviderTypeName + "_" + categoryName + "_routed"
```

2023-03-31 16:08 UTC, azrod commented on internal/provider/network/routed_datasource.go
> +func (d *networkRoutedDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
Refactor your schema and using SuperSchema

2023-03-31 16:08 UTC, azrod commented on internal/provider/network/routed_datasource.go
> +}
Add your necessary Meta Object (Org, Network, etc)

2023-04-05 09:37 UTC, eremid approved these changes

2023-04-05 09:37 UTC, eremid commented on internal/provider/common/network/schema.go
> +		_schema.Resource.MarkdownDescription = "Provides a Cloud Avenue VDC routed Network. This can be used to create, modify, and delete VDC routed networks."
VDC => vDC

2023-04-05 09:37 UTC, eremid commented on internal/provider/network/routed_datasource.go
> +			resp.State.RemoveResource(ctx)
`return`

2023-04-12 10:05 UTC, azrod approved these changes

2023-04-12 12:51 UTC, azrod requested changes

2023-04-12 12:51 UTC, azrod commented on internal/provider/network/common_network.go
> +}
```suggestion
func SetDataToNetworkRoutedModel(network *govcd.OpenApiOrgVdcNetwork) networkRoutedModel {
	return networkRoutedModel{
		ID:              types.StringValue(network.OpenApiOrgVdcNetwork.ID),
		Name:            types.StringValue(network.OpenApiOrgVdcNetwork.Name),
		Description:     utils.StringValueOrNull(network.OpenApiOrgVdcNetwork.Description),
		EdgeGatewayID:   types.StringValue(network.OpenApiOrgVdcNetwork.Connection.RouterRef.ID),
		EdgeGatewayName: types.StringValue(network.OpenApiOrgVdcNetwork.Connection.RouterRef.Name),
		InterfaceType:   types.StringValue(network.OpenApiOrgVdcNetwork.Connection.ConnectionType),
		Gateway:         types.StringValue(network.OpenApiOrgVdcNetwork.Subnets.Values[0].Gateway),
		PrefixLength:    types.Int64Value(int64(network.OpenApiOrgVdcNetwork.Subnets.Values[0].PrefixLength)),
		DNS1:            utils.StringValueOrNull(network.OpenApiOrgVdcNetwork.Subnets.Values[0].DNSServer1),
		DNS2:            utils.StringValueOrNull(network.OpenApiOrgVdcNetwork.Subnets.Values[0].DNSServer2),
		DNSSuffix:       utils.StringValueOrNull(network.OpenApiOrgVdcNetwork.Subnets.Values[0].DNSSuffix),
	}
}
```

2023-04-12 12:51 UTC, azrod commented on internal/provider/network/common_network.go
> +}
```suggestion
func GetIPRanges(network *govcd.OpenApiOrgVdcNetwork) []staticIPPool {
	ipPools := []staticIPPool{}

		for _, ipRange := range network.OpenApiOrgVdcNetwork.Subnets.Values[0].IPRanges.Values {
			ipPool := staticIPPool{
				StartAddress: types.StringValue(ipRange.StartAddress),
				EndAddress:   types.StringValue(ipRange.EndAddress),
			}
			ipPools = append(ipPools, ipPool)
		}
	return ipPools
}
```

2023-04-12 12:51 UTC, azrod commented on internal/provider/network/routed_datasource.go
> +//}
```suggestion
```

2023-04-12 12:51 UTC, azrod commented on internal/provider/network/routed_datasource.go
> +	// }
```suggestion
```

2023-04-12 12:51 UTC, azrod commented on internal/tests/network/routed_datasource_test.go
> +	edge_gateway_id = "urn:vcloud:gateway:dde5d31a-2f32-43ef-b3b3-127245958298"
Use datasource

2023-04-12 13:39 UTC, azrod approved these changes

2023-04-12 15:03 UTC, merged