feat: Add new resource
orange-cloudavenue/terraform-provider-cloudavenue pull request #474
Opened 2023-08-04 22:20 UTC by dmicheneau

### Description of your changes

If you submit change in the provider code, please make sure to:

- [ ] Write or modify examples in `examples/` directory
- [ ] Write or modify acceptance tests
- [ ] Run `make generate` to ensure the doc was updated properly

### How has this code been tested

2023-08-10 18:27 UTC, azrod requested changes

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	if plan.SecurityProfile.IsKnown() { // plan.SecurityType.Get() == profileCustom {
```suggestion
	if plan.SecurityProfile.IsKnown() {
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +		tflog.Info(ctx, "********************* [CREATE] Update VPN Tunnel Profile IPSec Security Profile")
```suggestion
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +		resp.Diagnostics.AddError("Error getting IPsec VPN Tunnel configuration from plan:", err.Error())
```suggestion
		resp.Diagnostics.AddError("Error getting IPsec VPN Tunnel configuration from plan", err.Error())
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	}
```suggestion
	if _, err = existingIPSecVPNConfiguration.Update(planVPNTunnel); err != nil {
		resp.Diagnostics.AddError("Error updating VPN Tunnel configuration", err.Error())
		return
	}
	
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	if err != nil && !govcd.ContainsNotFound(err) {
```suggestion
	if err != nil {
```

This is already tested

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +		}
```suggestion
		allRules, err := r.edgegw.GetAllIpSecVpnTunnels(nil)
		if err != nil {
			resp.Diagnostics.AddError("Failed to Get ALL VPN IPSec.", err.Error())
			return
		}
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	}
```suggestion
		listStr = getVPNIPSecTunnelsList(idParts[1], allRules)
		resp.Diagnostics.AddError("Failed to Get VPN IPSec."+listStr, err.Error())
		return
	}

```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +		diags.AddError("Error retrieving VPN Tunnel ID", err.Error())
```suggestion
		diags.AddError("Error retrieving VPN Tunnel", err.Error())
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	// ====== Get IPSec Profile
```suggestion
	// Get IPSec Profile
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	}
```go
	// Tunnel DH Groups
	if len(secProfile.TunnelConfiguration.DhGroups) > 0 {
		vpnTunnelSecProfile.TunnelDhGroups.Set(secProfile.TunnelConfiguration.DhGroups[0])
	}
	// Tunnel Digest Algorithms
	if len(secProfile.TunnelConfiguration.DigestAlgorithms) > 0 {
		vpnTunnelSecProfile.TunnelDigestAlgorithms.Set(secProfile.TunnelConfiguration.DigestAlgorithms[0])
	} else {
		vpnTunnelSecProfile.TunnelDigestAlgorithms.SetNull()
	}
	// Tunnel Encryption Algorithm
	if len(secProfile.TunnelConfiguration.EncryptionAlgorithms) > 0 {
		vpnTunnelSecProfile.TunnelEncryptionAlgorithms.Set(secProfile.TunnelConfiguration.EncryptionAlgorithms[0])
	}
```

Why TunnelDigestAlgorithms is set to Null if !> 0 while TunnelDhGroups and TunnelEncryptionAlgorithms no ?

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	}
```suggestion
	diags.Append(stateRefreshed.SecurityProfile.Set(ctx, vpnTunnelSecProfile)...)
	if diags.HasError() {
		return nil, true, diags
	}
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_schema.go
> +					Computed: true,
```suggestion
```

Already compute

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_schema.go
> +			},
```go
			"pre_shared_key": superschema.SuperStringAttribute{
				Common: &schemaR.StringAttribute{
					MarkdownDescription: "The Pre-Shared Key (PSK) is an Authentication method. Is a complex password (ASCII) that will be exchanged between both sites in order to set up the IPsec tunnel.",
				},
				Resource: &schemaR.StringAttribute{
					Required:  true,
					Sensitive: true,
				},
				DataSource: &schemaD.StringAttribute{
					Computed: true,
				},
			},
```

`pre_shared_key` does not require a minimum size ?

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_schema.go
> +					MarkdownDescription: "Security type which is use for IPsec VPN Tunnel. Let empty if you want to use the default configuration.",
```suggestion
					MarkdownDescription: "Security type which is use for IPsec VPN Tunnel.",
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_schema.go
> +					// },
```suggestion
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_schema.go
If Resource and Datesource have Computed = true move this setting to Common section

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_schema.go
> +					},
Add validator between 3 -> 60

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_schema_test.go
Add TestSchema for Datasource

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_types.go
> +	// CertificateID      supertypes.StringValue       `tfsdk:"certificate_id"`
```suggestion
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_types.go
> +func NewVPNIPSec(t any) *VPNIPSecModel {
```suggestion
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_types.go
> +	}
```suggestion
	values = &govcdtypes.NsxtIpSecVpnTunnelSecurityProfile{}
	if !rm.SecurityProfile.IsKnown() {
		return
	}

	securityProfile, d := rm.GetSecurityProfile(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return
	}
```

2023-08-10 18:27 UTC, azrod commented on internal/provider/edgegw/vpn_ipsec_types.go
> +}
```suggestion
func (rm *VPNIPSecModel) ToNsxtIPSecVPNTunnel(ctx context.Context) (values *govcdtypes.NsxtIpSecVpnTunnel, diags diag.Diagnostics) {
	values = &govcdtypes.NsxtIpSecVpnTunnel{
		Name:                    rm.Name.Get(),
		Description:             rm.Description.Get(),
		Enabled:                 rm.Enabled.Get(),
		PreSharedKey:            rm.PreSharedKey.Get(),
		Logging:                 false,             // not available on cloudavenue
		AuthenticationMode:      vpnAuthentication, // Only PSK is supported on cloudavenue
		ConnectorInitiationMode: vpnModeInit,
	}

	if rm.ID.IsKnown() {
		values.ID = rm.ID.Get()
	}

	// Get local networks
	localNet, d := rm.GetLocalNetworks(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return
	}
	values.LocalEndpoint.LocalId = rm.LocalIPAddress.Get()
	values.LocalEndpoint.LocalAddress = rm.LocalIPAddress.Get()
	values.LocalEndpoint.LocalNetworks = localNet.Get()

	// Get remote networks
	remoteNet, diags := rm.GetRemoteNetworks(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return
	}
	values.RemoteEndpoint.RemoteId = rm.RemoteIPAddress.Get()
	values.RemoteEndpoint.RemoteAddress = rm.RemoteIPAddress.Get()
	values.RemoteEndpoint.RemoteNetworks = remoteNet.Get()

	return
}
```

2023-08-10 18:53 UTC, dmicheneau commented on internal/provider/edgegw/vpn_ipsec_resource.go
> +	ipSecVPNConfig, err = plan.ToNsxtIPSecVPNTunnel(ctx)
i use the var declared to force the import of gocvdtype, and to see the difference between govcdtype and govcd struct

2023-08-11 09:06 UTC, azrod commented on internal/tests/edgegw/vpn_ipsec_resource_test.go
> +// `
```suggestion
```

2023-08-11 09:20 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 09:27 UTC, valentin-dubreuil commented
## :bangbang: Acceptance Test failed 

=== RUN   TestAccVPNIPSecResource
    vpn_ipsec_resource_test.go:283: Step 4/10 error: Error running pre-apply refresh: exit status 1
        
        Error: Invalid Attribute Value
        
          with cloudavenue_edgegateway_vpn_ipsec.example,
          on terraform_plugin_test.tf line 32, in resource "cloudavenue_edgegateway_vpn_ipsec" "example":
          32: resource "cloudavenue_edgegateway_vpn_ipsec" "example" {
        
        Attribute security_profile.tunnel_sa_lifetime value must be between 21600 and
        31536000, got: 3600
    testing_new.go:85: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: Invalid Attribute Value
        
          with cloudavenue_edgegateway_vpn_ipsec.example,
          on terraform_plugin_test.tf line 32, in resource "cloudavenue_edgegateway_vpn_ipsec" "example":
          32: resource "cloudavenue_edgegateway_vpn_ipsec" "example" {
        
        Attribute security_profile.tunnel_sa_lifetime value must be between 21600 and
        31536000, got: 3600
--- FAIL: TestAccVPNIPSecResource (368.25s)
FAIL
FAIL	github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw	368.261s
FAIL

2023-08-11 09:43 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 09:46 UTC, azrod approved these changes

2023-08-11 09:53 UTC, valentin-dubreuil commented
## :bangbang: Acceptance Test failed 

=== RUN   TestAccVPNIPSecResource
panic: test timed out after 10m0s
running tests:
	TestAccVPNIPSecResource (10m0s)

goroutine 2404 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.7/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000334000, {0x12ce8ce?, 0x529d25?}, 0x13542c0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x1cd90a0?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc000334000, 0xc00031fc88)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0002fedc0?, {0x1cc96a0, 0x12, 0x12}, {0xc000259448?, 0x100c00031fd10?, 0x1cd8480?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0002fedc0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:81 +0x1aa

goroutine 21 [semacquire]:
sync.runtime_Semacquire(0xc0006d3130?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc0000be420?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/sync/waitgroup.go:116 +0x4b
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).runTerraformCmd(0xc00027dc70, {0x14afe80, 0xc00012a000}, 0xc0000be420)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd_linux.go:75 +0x4d5
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).Refresh(0x14afef0?, {0x14afe80, 0xc00012a000}, {0xc0005b2318?, 0x12e814a?, 0x25?})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/refresh.go:80 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugintest.(*WorkingDir).Refresh(0xc000092140, {0x14afef0, 0xc000495860})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/internal/plugintest/working_dir.go:353 +0xe7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig.func1()
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new_config.go:30 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runProviderCommand({0x14afef0, 0xc000495860}, {0x14bb260, 0xc0003341a0}, 0xc0005b4048, 0xc000092140, 0xc0005b45b8)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/plugin.go:437 +0x27eb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig({_, _}, {_, _}, {0x0, 0xc0002414e0, 0x0, 0x0, 0xc00024a720, 0x0, ...}, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new_config.go:29 +0x1e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runNewTest({0x14afef0, 0xc000495860}, {0x14bb260, 0xc0003341a0}, {0x0, 0xc0002414e0, 0x0, 0x0, 0xc00024a720, 0x0, ...}, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new.go:287 +0x12f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.Test({0x14bb260, 0xc0003341a0}, {0x0, 0xc0002414e0, 0x0, 0x0, 0xc00024a720, 0x0, 0x0, 0x0, ...})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing.go:779 +0x64f
github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw.TestAccVPNIPSecResource(0xc0003341a0)
	/home/runner/work/terraform-provider-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw/vpn_ipsec_resource_test.go:283 +0xd27
testing.tRunner(0xc0003341a0, 0x13542c0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1629 +0x3ea

goroutine 2063 [select]:
net/http.(*persistConn).writeLoop(0xc000524d80)
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/http/transport.go:1766 +0x173d

goroutine 2335 [IO wait]:
internal/poll.runtime_pollWait(0x7fea44c4f418, 0x72)
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000378d00?, 0xc000360000?, 0x0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000378d00, {0xc000360000, 0x8000, 0x8000})
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc000378d00, {0xc000360000?, 0xc000076cc8?, 0x418110?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0000144a8, {0xc000360000?, 0x43c2c0?, 0xc000105040?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc0007d4c60, {0xc0004f0580, 0x9, 0xc000076d30?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x14a5dc0, 0xc0007d4c60}, {0xc0004f0580, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.20.7/x64/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.20.7/x64/src/io/io.go:351
golang.org/x/net/http2.readFrameHeader({0xc0004f0580?, 0x9?, 0xc000076da0?}, {0x14a5dc0?, 0xc0007d4c60?})
	/home/runner/go/pkg/mod/golang.org/x/net@v0.14.0/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004f0540)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.14.0/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc00055e4e0, 0xc0004907e0?, 0xc000076f40?)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/http2_server.go:642 +0x167
google.golang.org/grpc.(*Server).serveStreams(0xc0002663c0, {0x14b6e98?, 0xc00055e4e0})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:946 +0x162
google.golang.org/grpc.(*Server).handleRawConn.func1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:889 +0x46
created by google.golang.org/grpc.(*Server).handleRawConn
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:888 +0x185

goroutine 2193 [IO wait]:
internal/poll.runtime_pollWait(0x7fea44fccfa0, 0x72)
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0003dcd00?, 0xc00053e000?, 0x0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0003dcd00, {0xc00053e000, 0x2000, 0x2000})
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc0003dcd00, {0xc00053e000?, 0xc00053e00d?, 0x22e?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000014568, {0xc00053e000?, 0x1ff3?, 0xc00053e005?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0003807e0, {0xc00053e000?, 0xc0003807e0?, 0x0?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc00034a610, {0x14a5fc0, 0xc0003807e0})
	/opt/hostedtoolcache/go/1.20.7/x64/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00034a380, {0x14a8d00?, 0xc000014568}, 0x0?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00034a380, 0x0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.20.7/x64/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc00034a380, {0xc00034c000, 0x1000, 0x2c?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/crypto/tls/conn.go:1316 +0x16f
net/http.(*persistConn).Read(0xc000300d80, {0xc00034c000?, 0xc00062ea80?, 0xc000750d30?})
	/opt/hoste [...]

2023-08-11 10:07 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 10:07 UTC, valentin-dubreuil commented
## :bangbang: Acceptance Test failed 

=== RUN   TestAccVPNIPSecResource
    vpn_ipsec_resource_test.go:283: Step 1/10 error: Error running apply: exit status 1
        
        Error: This vDC conflict with an already existing vDC (HTTP Code => 409)
        
          with cloudavenue_vdc.example,
          on terraform_plugin_test.tf line 2, in resource "cloudavenue_vdc" "example":
           2: resource "cloudavenue_vdc" "example" {
        
        Organization cav01ev01ocb0006205 already owns a vDC named MyVDC1
--- FAIL: TestAccVPNIPSecResource (9.22s)
FAIL
FAIL	github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw	9.223s
FAIL

2023-08-11 12:16 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 12:26 UTC, valentin-dubreuil commented
## :bangbang: Acceptance Test failed 

=== RUN   TestAccVPNIPSecResource
panic: test timed out after 10m0s
running tests:
	TestAccVPNIPSecResource (10m0s)

goroutine 1990 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.7/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000107ba0, {0x12ce8ce?, 0x529d25?}, 0x13542c0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x1cd90a0?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc000107ba0, 0xc00031fc88)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0002fcf00?, {0x1cc96a0, 0x12, 0x12}, {0xc000259448?, 0x100c00031fd10?, 0x1cd8480?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0002fcf00)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:81 +0x1aa

goroutine 19 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc000348a00?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc0000be580?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/sync/waitgroup.go:116 +0x4b
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).runTerraformCmd(0xc00027dd40, {0x14afe80, 0xc000126000}, 0xc0000be580)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd_linux.go:75 +0x4d5
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).Apply(0x14afef0?, {0x14afe80, 0xc000126000}, {0xc0003ae280?, 0x12e460c?, 0x23?})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/apply.go:100 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugintest.(*WorkingDir).Apply(0xc000094140, {0x14afef0, 0xc0001ce630})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/internal/plugintest/working_dir.go:244 +0x1e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig.func4()
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new_config.go:70 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runProviderCommand({0x14afef0, 0xc0001ce630}, {0x14bb260, 0xc000107d40}, 0xc000570048, 0xc000094140, 0xc0005705b8)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/plugin.go:437 +0x27eb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig({_, _}, {_, _}, {0x0, 0xc0002414c0, 0x0, 0x0, 0xc0002fe720, 0x0, ...}, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new_config.go:69 +0x565
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runNewTest({0x14afef0, 0xc0001ce630}, {0x14bb260, 0xc000107d40}, {0x0, 0xc0002414c0, 0x0, 0x0, 0xc0002fe720, 0x0, ...}, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new.go:287 +0x12f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.Test({0x14bb260, 0xc000107d40}, {0x0, 0xc0002414c0, 0x0, 0x0, 0xc0002fe720, 0x0, 0x0, 0x0, ...})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing.go:779 +0x64f
github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw.TestAccVPNIPSecResource(0xc000107d40)
	/home/runner/work/terraform-provider-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw/vpn_ipsec_resource_test.go:283 +0xd27
testing.tRunner(0xc000107d40, 0x13542c0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1629 +0x3ea

goroutine 1939 [chan receive, 1 minutes]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runProviderCommand.func6(0xc0003ae240?)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/plugin.go:413 +0x25
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runProviderCommand
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/plugin.go:412 +0x260a

goroutine 1933 [select, 1 minutes]:
github.com/hashicorp/go-plugin.Serve(0xc000270360)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.10/server.go:474 +0x14e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.Serve({0xc000352450, 0x2b}, 0xc0004a4240, {0xc0003ae140, 0x3, 0x4})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:315 +0xc25
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf6serverServe(0xc0002702a0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/plugin/serve.go:237 +0x4d9
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc0002702a0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/plugin/serve.go:132 +0x1a5
created by github.com/hashicorp/terraform-plugin-sdk/v2/plugin.DebugServe
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/plugin/debug.go:47 +0x17c

goroutine 1943 [select, 1 minutes]:
github.com/hashicorp/terraform-exec/tfexec.writeOutput.func1()
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd.go:250 +0xa6
created by github.com/hashicorp/terraform-exec/tfexec.writeOutput
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd.go:249 +0x14a

goroutine 1934 [chan receive, 1 minutes]:
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf6serverServe.func1()
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/plugin/serve.go:214 +0x2b
created by github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf6serverServe
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/plugin/serve.go:211 +0x23c

goroutine 1945 [select, 1 minutes]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000348be0, 0x1)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/controlbuf.go:418 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc00014a070)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/controlbuf.go:552 +0x91
google.golang.org/grpc/internal/transport.NewServerTransport.func2()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/http2_server.go:341 +0xda
created by google.golang.org/grpc/internal/transport.NewServerTransport
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/http2_server.go:338 +0x1bb3

goroutine 1632 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc00059c7e0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.20.7/x64/src/net/http/transport.go:1766 +0x173d

goroutine 1921 [select, 1 minutes]:
github.com/hashicorp/go-plugin.(*grpcStdioServer).StreamStdio(0xc0001aeba0, 0x11b2ea0?, {0x14b4f30, 0xc0001aebc0})
	/home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.10/grpc_stdio.go:61 +0x11d
github.com/hashicorp/go-plugin/internal/plugin._GRPCStdio_StreamStdio_Handler({0x11290a0?, 0xc0001aeba0}, {0x14b2e30, 0xc0003b4870})
	/home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.10/internal/plugin/grpc_stdio.pb.go:185 +0xd0
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000426000, {0x14b6e98, 0xc0004711e0}, 0xc0001d8000, 0xc0001cec30, 0x1cbefa0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1631 +0x1384
google.golang.org/grpc.(*Server).handleStream(0xc000426000, {0x14b6e98, 0xc0004711e0}, 0xc0001d8000, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1718 +0x9f0
google.golang.org/grpc.(*Server).serveStreams [...]

2023-08-11 12:44 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 12:45 UTC, valentin-dubreuil commented
## :bangbang: Acceptance Test failed 

=== RUN   TestAccVPNIPSecResource
    vpn_ipsec_resource_test.go:283: Step 1/10 error: Error running apply: exit status 1
        
        Error: This vDC conflict with an already existing vDC (HTTP Code => 409)
        
          with cloudavenue_vdc.example,
          on terraform_plugin_test.tf line 2, in resource "cloudavenue_vdc" "example":
           2: resource "cloudavenue_vdc" "example" {
        
        Organization cav01ev01ocb0006205 already owns a vDC named MyVDC1
--- FAIL: TestAccVPNIPSecResource (7.92s)
FAIL
FAIL	github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw	7.924s
FAIL

2023-08-11 12:49 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 13:43 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 13:44 UTC, valentin-dubreuil commented
## :bangbang: Acceptance Test failed 

=== RUN   TestAccVPNIPSecResource
    vpn_ipsec_resource_test.go:283: Step 1/10 error: Error running apply: exit status 1
        
        Error: This vDC conflict with an already existing vDC (HTTP Code => 409)
        
          with cloudavenue_vdc.example,
          on terraform_plugin_test.tf line 2, in resource "cloudavenue_vdc" "example":
           2: resource "cloudavenue_vdc" "example" {
        
        Organization cav01ev01ocb0006205 already owns a vDC named MyVDC1
--- FAIL: TestAccVPNIPSecResource (8.99s)
FAIL
FAIL	github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw	8.995s
FAIL

2023-08-11 13:46 UTC, dmicheneau commented
/testacc TestAccVPNIPSecResource

2023-08-11 13:56 UTC, valentin-dubreuil commented
## :bangbang: Acceptance Test failed 

=== RUN   TestAccVPNIPSecResource
panic: test timed out after 10m0s
running tests:
	TestAccVPNIPSecResource (10m0s)

goroutine 1975 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.7/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000107a00, {0x12ce8ce?, 0x529d25?}, 0x13542c0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x1cd90a0?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc000107a00, 0xc00031fc88)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0002fefa0?, {0x1cc96a0, 0x12, 0x12}, {0xc000259458?, 0x100c00031fd10?, 0x1cd8480?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0002fefa0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:81 +0x1aa

goroutine 19 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc00057e640?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc0000249a0?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/sync/waitgroup.go:116 +0x4b
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).runTerraformCmd(0xc000281a00, {0x14afe80, 0xc000126000}, 0xc0000249a0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd_linux.go:75 +0x4d5
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).Apply(0x14afef0?, {0x14afe80, 0xc000126000}, {0xc000162680?, 0x12e460c?, 0x23?})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/apply.go:100 +0x59
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugintest.(*WorkingDir).Apply(0xc0000b80f0, {0x14afef0, 0xc0001c08a0})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/internal/plugintest/working_dir.go:244 +0x1e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig.func4()
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new_config.go:70 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runProviderCommand({0x14afef0, 0xc0001c08a0}, {0x14bb260, 0xc000107ba0}, 0xc000616048, 0xc0000b80f0, 0xc0006165b8)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/plugin.go:437 +0x27eb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig({_, _}, {_, _}, {0x0, 0xc0002b54c0, 0x0, 0x0, 0xc00024a720, 0x0, ...}, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new_config.go:69 +0x565
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runNewTest({0x14afef0, 0xc0001c08a0}, {0x14bb260, 0xc000107ba0}, {0x0, 0xc0002b54c0, 0x0, 0x0, 0xc00024a720, 0x0, ...}, ...)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing_new.go:287 +0x12f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.Test({0x14bb260, 0xc000107ba0}, {0x0, 0xc0002b54c0, 0x0, 0x0, 0xc00024a720, 0x0, 0x0, 0x0, ...})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/testing.go:779 +0x64f
github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw.TestAccVPNIPSecResource(0xc000107ba0)
	/home/runner/work/terraform-provider-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw/vpn_ipsec_resource_test.go:283 +0xd27
testing.tRunner(0xc000107ba0, 0x13542c0)
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.7/x64/src/testing/testing.go:1629 +0x3ea

goroutine 1925 [select, 3 minutes]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0xc00057e280?)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.10/grpc_broker.go:124 +0x67
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc00057e4b0)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.10/grpc_broker.go:414 +0x44
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
	/home/runner/go/pkg/mod/github.com/hashicorp/go-plugin@v1.4.10/grpc_server.go:88 +0x46a

goroutine 1923 [chan receive, 3 minutes]:
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf6serverServe.func1()
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/plugin/serve.go:214 +0x2b
created by github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf6serverServe
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/plugin/serve.go:211 +0x23c

goroutine 1929 [chan receive, 3 minutes]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runProviderCommand.func6(0xc000162200?)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/plugin.go:413 +0x25
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runProviderCommand
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/resource/plugin.go:412 +0x260a

goroutine 1931 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x7fdda405c450, 0x72)
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0005ea480?, 0xc000315000?, 0x1)
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0005ea480, {0xc000315000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.20.7/x64/src/internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
	/opt/hostedtoolcache/go/1.20.7/x64/src/os/file_posix.go:31
os.(*File).Read(0xc0000144a8, {0xc000315000?, 0xc000576cf0?, 0x432d70?})
	/opt/hostedtoolcache/go/1.20.7/x64/src/os/file.go:118 +0x5e
bufio.(*Reader).fill(0xc000576f08)
	/opt/hostedtoolcache/go/1.20.7/x64/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).ReadSlice(0xc000576f08, 0x18?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/bufio/bufio.go:372 +0x2f
bufio.(*Reader).collectFragments(0x38?, 0x6d?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/bufio/bufio.go:447 +0x74
bufio.(*Reader).ReadBytes(0x14afe80?, 0x0?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/bufio/bufio.go:474 +0x1d
github.com/hashicorp/terraform-exec/tfexec.writeOutput({0x14afe80?, 0xc000126000}, {0x14ac4b8?, 0xc0000144a8}, {0x14a9100, 0xc000397280})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd.go:260 +0x294
github.com/hashicorp/terraform-exec/tfexec.(*Terraform).runTerraformCmd.func2()
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd_linux.go:70 +0x79
created by github.com/hashicorp/terraform-exec/tfexec.(*Terraform).runTerraformCmd
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-exec@v0.18.1/tfexec/cmd_linux.go:68 +0x4cb

goroutine 1935 [select, 3 minutes]:
google.golang.org/grpc/internal/transport.(*recvBufferReader).read(0xc00057ea50, {0xc0003eabb0, 0x5, 0x5})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/transport.go:183 +0x90
google.golang.org/grpc/internal/transport.(*recvBufferReader).Read(0xc00057ea50, {0xc0003eabb0?, 0xc000337950?, 0xc00019b668?})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/transport.go:177 +0x178
google.golang.org/grpc/internal/transport.(*transportReader).Read(0xc00044b4a0, {0xc0003eabb0?, 0xc00019b6e0?, 0xb57567?})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/internal/transport/transport.go:514 +0x32
io.ReadAtLeast({0x14a83c0, 0xc00044b4a0}, {0xc0003eabb0, 0x5, 0x5}, 0x5)
	/opt/hostedtoolcache/go/1.20.7/x64/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.20.7/x64/src/io/io.go:351
google.golang.org/grpc/internal/transport.(*Strea [...]

2023-08-11 13:58 UTC, dmicheneau commented
go test have a timeout set by default to 10 min. However this test take more... and no fix seems appear about this problem.

2023-08-11 14:33 UTC, azrod approved these changes

2023-08-11 14:33 UTC, merged